# Generated by Django 5.1.1 on 2024-10-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='account_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
