# Generated by Django 5.1.1 on 2024-10-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_reader_account_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(default=2000),
        ),
    ]
