# Generated by Django 5.1.1 on 2024-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_book_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRecord',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('reader_id', models.CharField(max_length=255)),
                ('reader_name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('num_books', models.IntegerField()),
                ('book_list', models.TextField()),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
