# Generated by Django 5.1.1 on 2024-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_checkoutrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
