# Generated by Django 5.1.1 on 2024-10-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_remove_checkoutrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutrecord',
            options={'verbose_name': 'Return Record', 'verbose_name_plural': 'Return Records'},
        ),
    ]
