# Generated by Django 5.1.1 on 2024-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_alter_checkoutrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrecord',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='return_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
